In [2]:
import numpy as np

## numpy array

In [3]:
myList = [20, 30, 40]

In [4]:
np.array(myList)

array([20, 30, 40])

In [5]:
matrixList = [[10, 20, 30], [20, 30, 40], [30, 40, 50]]

In [6]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.zeros((9, 9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## ones

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((9, 9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [15]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

## eye

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [19]:
np.random.randn(4)

array([ 0.03581448, -0.29799815, -0.4180062 , -0.17406081])

In [18]:
np.random.randn(4, 4)

array([[ 0.11624485,  0.49001104, -0.42740765,  0.35080317],
       [-0.04827981,  0.74869795,  0.09356683,  0.05750355],
       [-0.0563052 ,  3.41858311,  0.16369039, -0.39608541],
       [-0.09238409,  0.51196877,  0.2714727 ,  0.2515132 ]])

In [20]:
np.random.randint(1, 10)

8

In [21]:
np.random.randint(1, 10, 5)

array([3, 6, 1, 4, 2])

In [27]:
myNumpyArray = np.arange(30)

In [28]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
myRandomArray = np.random.randint(0, 100, 30)

In [25]:
myRandomArray

array([90, 38, 73, 92, 39, 60, 68, 14, 58, 81, 77, 68, 35, 64, 67,  1, 76,
       37, 24, 23, 96, 14, 12, 77, 32, 87, 34, 21, 62, 57])

## Numpy Array Methods

In [31]:
myNumpyArray.reshape(5, 5)

ValueError: cannot reshape array of size 30 into shape (5,5)

In [30]:
myNumpyArray.reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
myNumpyArray.max()

29

In [33]:
myRandomArray.max()

96

In [34]:
myRandomArray.min()

1

In [35]:
myRandomArray.argmax()

20

In [36]:
myRandomArray.argmin()

15

In [37]:
myNumpyArray.shape

(30,)

In [39]:
myReshapedNumpyArray = myNumpyArray.reshape(5, 6)

In [40]:
myReshapedNumpyArray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])