In [5]:
import numpy as np

In [6]:
myArray = np.arange(0, 15)

In [9]:
myArray[3: 5]

array([3, 4])

In [10]:
myArray[3: 8] = -5

In [11]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [17]:
anotherArray = np.arange(0, 24)

In [18]:
slicingArray = anotherArray[4: 9]

In [20]:
slicingArray[:] = 700

In [21]:
slicingArray

array([700, 700, 700, 700, 700])

In [22]:
anotherArray

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [23]:
exampleArray = np.arange(0, 24)

In [24]:
copyExampleArray = exampleArray.copy()

In [25]:
copyExampleArraySlicing = copyExampleArray[3: 6]

In [26]:
copyExampleArraySlicing[:] = 800

In [27]:
copyExampleArraySlicing

array([800, 800, 800])

In [28]:
copyExampleArray

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [29]:
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [30]:
myList = [[10, 20, 30], [20, 30, 40], [40, 50, 60]]

In [31]:
myMatrixArray = np.array(myList)

In [32]:
myMatrixArray

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [33]:
myMatrixArray[0]

array([10, 20, 30])

In [35]:
myMatrixArray[1][2]

40

In [36]:
myMatrixArray[1, 2]

40

In [37]:
myMatrixArray[1:, 2]

array([40, 60])

In [40]:
newList = [list(range(0,5)), list(range(5,10)), list(range(10,15)), list(range(15,20)), list(range(20,25))]

In [43]:
newMatrix = np.array(newList)

In [44]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
newMatrix[[0, 2, 4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operations

In [47]:
oneArray = np.random.randint(1, 100, 20)

In [48]:
oneArray > 24

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True])

In [49]:
resultArray = oneArray > 24

In [50]:
oneArray[resultArray]

array([33, 91, 26, 75, 39, 83, 41, 84, 30, 60, 71, 56, 83, 60, 74, 75, 86])

In [51]:
oneArray[oneArray > 24]

array([33, 91, 26, 75, 39, 83, 41, 84, 30, 60, 71, 56, 83, 60, 74, 75, 86])

In [52]:
array = np.arange(0, 24)

In [53]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [54]:
array * array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [55]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [56]:
array / array

<ipython-input-56-467fdf4efc53>:1: RuntimeWarning: invalid value encountered in true_divide
  array / array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [58]:
np.max(array)

23

In [59]:
np.min(array)

0